export const Colors = {
    border_color:'gray',
    primary_blue:'#00BFFF',
    black:'#000000',
    light_grey:'#F8F8F8',
    white:'#FFFFFF',
    link:'green',
    twitter_blue:'#1DA1F2',
    facebook_blue:'#3C5A99',
    red:'red',
    btn_color:'#006666',
    grey:'#F2F2F2', 
    white:'#FFF',
    black:'#000',
    green:'green',
    gray:'gray',
    pink:'pink',
    yellow:'yellow',
    skyblue: 'skyblue',
}